---
- name: executing script for Docker Installation
  hosts: all
  become: true
  tasks:
    - script: docker.sh

- name: executing script for installation of Kubernetes on k8s-master
  hosts: k8sm
  become: true
  tasks:
    - script: master.sh

- name: executing script for k8s installation on slaves
  hosts: k8ss
  become: true
  tasks:
    - script: worker.sh
